### ISSUE TITLE
 Cannot install v0.3.1 due to `error[E0308]: mismatched types`

### ISSUE THREAD

**Issue by Buckram123** [tfpk/mdbook-keeper#12]
Similar to #10
Here's the error from Github Action: https://github.com/AbstractSDK/cw-orchestrator/actions/runs/5799906229/job/15720911479#step:7:596
Same error locally

**Comment by rcoh** [comment]
a workaround is `cargo install --locked mdbook-keeper` but should probably determine the root cause

**Comment by tfpk** [comment]
Looking into this now...

**Comment by tfpk** [comment]
The cause of this is: https://github.com/rust-lang/mdBook/issues/2037
I've fixed this in `tfpk/fix-toml-build-failure` (made a mistake in not PR'ing it).
Please let me know if this doesn't fix it.

**Comment by tfpk** [comment]
@rparrett 

Finally got around to looking at this.

I didn't release a new version with the pinned toml.... my bad. I'm doing so now.
